# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-pr:
    docker:
    # specify the version you desire here
    - image: circleci/node:10

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v3-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v3-dependencies-

    - run:
        name: Install dependencies
        command: npm install

    - save_cache:
        paths:
        - node_modules
        key: v3-dependencies-{{ checksum "package.json" }}

    - run:
        name: Lint application
        command: npm run lint

    - run:
        name: Building application
        command: npm run build:prod

  build-staging:
    docker:
    # specify the version you desire here
    - image: docker:17.05.0-ce-git

    steps:
    - checkout
    - setup_remote_docker

    - run:
        no_output_timeout: 20m
        name: Building docker image
        command: docker build -t polyhx/csgames-dashboard:latest -f Dockerfile.staging .
    - run:
        name: Pushing docker image
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push polyhx/csgames-dashboard:latest

  build-prod:
    docker:
    # specify the version you desire here
    - image: docker:17.05.0-ce-git

    steps:
    - checkout
    - setup_remote_docker

    - run:
        no_output_timeout: 20m
        name: Building docker image
        command: docker build -t polyhx/csgames-dashboard:$CIRCLE_TAG .
    - run:
        name: Pushing docker image
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push polyhx/csgames-dashboard:$CIRCLE_TAG

workflows:
  version: 2
  build-always:
    jobs:
    - build-pr:
        filters:
          branches:
            ignore:
            - master
          tags:
            ignore: /.*/
  build-staging-if-master:
    jobs:
    - build-staging:
        filters:
          branches:
            only:
            - master
          tags:
            ignore: /.*/
  build-prod-if-tags:
    jobs:
    - build-prod:
        filters:
          tags:
            only: /^v([0-9.]+)$/
          branches:
            ignore: /.*/
